# Generated by Django 3.0.2 on 2020-02-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falconpi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cruduser',
            old_name='name',
            new_name='Username',
        ),
        migrations.RenameField(
            model_name='cruduser',
            old_name='address',
            new_name='cncuser',
        ),
        migrations.RenameField(
            model_name='cruduser',
            old_name='age',
            new_name='monitoringport',
        ),
        migrations.AddField(
            model_name='cruduser',
            name='cncip',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cruduser',
            name='funame',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cruduser',
            name='fupass',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
